// Generated by https://quicktype.io

export interface StreamOnlineNotificationPayload {
  subscription: Subscription
  event: Event
}

export interface Event {
  id: string
  broadcaster_user_id: string
  broadcaster_user_login: string
  broadcaster_user_name: string
  type: string
  started_at: string
}

export interface Subscription {
  id: string
  type: string
  version: string
  status: string
  cost: number
  condition: Condition
  transport: Transport
  created_at: string
}

export interface Condition {
  broadcaster_user_id: string
}

export interface Transport {
  method: string
  callback: string
}
